### ISSUE TITLE
Search feature stopped working after upgrade

### ISSUE THREAD

**Issue by timhux123** [CIRCL/AIL-framework#119]
I completed 'git pull' inside of the virtual env. and the update ran without issue. All appears to be working except for the search feature (using the search box in the upper left corner of the webpage.) 

The webpage displayed after the failed search reports: 

"Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

The console the flask server is running under reports:

"ERROR in app: Exception on /search [POST]\
Traceback (most recent call last):\
  File "/AIL-framework/AILENV/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app\
    response = self.full_dispatch_request()\
  File "/AIL-framework/AILENV/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request\
    rv = self.handle_user_exception(e)\
  File "/AIL-framework/AILENV/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception\
    reraise(exc_type, exc_value, tb)\
  File "/AIL-framework/AILENV/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request\
    rv = self.dispatch_request()\
  File "/AIL-framework/AILENV/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request\
    return self.view_functions[rule.endpoint](**req.view_args)\
  File "./Flasks/Flask_search.py", line 101, in search\
    selected_index = get_current_index()\
  File "./Flasks/Flask_search.py", line 35, in get_current_index\
    with open(indexRegister_path, "r") as f:\
IOError: [Errno 2] No such file or directory: '/AIL-framework/indexdir/all_index.txt'\"

I do have a /AIL-framework/indexdir/ directory but there is no all_index.txt located here. There are many large MAIN_<random characters>.seg files in this directory along with _MAIN_<random numbers>.toc and a MAIN_WRITELOCK.

I also notice the new "config.cfg" file created after the upgrade has a few new lines than my backup .cfg file does not have:

# Indexer configuration
[Indexer]
type = whoosh
path = indexdir
register = indexdir/all_index.txt  -->NEW LINE AFTER THE UPGRADE
#size in Mb  -->NEW LINE AFTER THE UPGRADE
index_max_size = 2000  -->NEW LINE AFTER THE UPGRADE

**Comment by mokaddem** [comment]
Thanks for the feedback,
The pull request #114 introduced a new behavior for the indexer. This module is responsible for the search feature.
Did you run the new version of `Indexer.py` yet ?

**Comment by SteveClement** [comment]
Dear @timhux123 is this issue still open for you?

**Comment by SteveClement** [comment]
@timhux123 final #bump
