### ISSUE TITLE
Training VM search returns HTTP 500

### ISSUE THREAD

**Issue by cudeso** [CIRCL/AIL-framework#125]
Hi,

The VM from https://www.circl.lu/services/ail-training-materials/#ail-virtual-machine returns a HTTP/500 when doing a search (left-upper search field).
This does not happen on a manual install of AIL (latest 6-Jul).

[2017-07-08 23:49:08,531] ERROR in app: Exception on /search [POST]
Traceback (most recent call last):
  File "/home/ail/AIL-framework/AILENV/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ail/AIL-framework/AILENV/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ail/AIL-framework/AILENV/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ail/AIL-framework/AILENV/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ail/AIL-framework/AILENV/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./Flasks/Flask_search.py", line 120, in search
    ix = index.open_dir(selected_index)
  File "/home/ail/AIL-framework/AILENV/local/lib/python2.7/site-packages/whoosh/index.py", line 123, in open_dir
    return FileIndex(storage, schema=schema, indexname=indexname)
  File "/home/ail/AIL-framework/AILENV/local/lib/python2.7/site-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/home/ail/AIL-framework/AILENV/local/lib/python2.7/site-packages/whoosh/index.py", line 632, in read
    check_size("int", _INT_SIZE)
  File "/home/ail/AIL-framework/AILENV/local/lib/python2.7/site-packages/whoosh/index.py", line 626, in check_size
    sz = stream.read_varint()
  File "/home/ail/AIL-framework/AILENV/local/lib/python2.7/site-packages/whoosh/filedb/structfile.py", line 191, in read_varint
    return read_varint(self.read)
  File "/home/ail/AIL-framework/AILENV/local/lib/python2.7/site-packages/whoosh/util/varints.py", line 102, in read_varint
    b = ord(readfn(1))
TypeError: ord() expected a character, but string of length 0 found

**Comment by SteveClement** [comment]
Thanks for the bug report. 👍 We'll check it and fix it.

**Comment by mokaddem** [comment]
It seems that the Whoosh index of the VM is corrupted. Can you try to delete all content located in the ```AIL-framework/indexdir``` and see if it works?

**Comment by adulau** [comment]
The VM has been updated. Feel free to test again and reopen the issue if this is not fixed.
