### ISSUE TITLE
Tokenizer issue

### ISSUE THREAD

**Issue by adulau** [CIRCL/AIL-framework#130]
~~~~
Traceback (most recent call last):
  File "./Tokenize.py", line 52, in <module>
    message = p.get_from_set()
  File "/home/adulau/git/AIL-framework/bin/Helper.py", line 180, in get_from_set
    self.r_temp.sadd("MODULE_TYPE_"+self.subscriber_name, str(self.moduleNum))
  File "/home/adulau/git/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/client.py", line 1494, in sadd
    return self.execute_command('SADD', name, *values)
  File "/home/adulau/git/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/adulau/git/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/client.py", line 587, in parse_response
    return self.response_callbacks[command_name](response, **options)
ValueError: invalid literal for int() with base 10: 'OK'

~~~~

**Comment by Terrtia** [comment]
It should be fixed in the recent version of AIL.
