### ISSUE TITLE
Error in Duplicates.py

### ISSUE THREAD

**Issue by jeromeleonard** [CIRCL/AIL-framework#176]
OS: Ubuntu 16.04
installed with git clone and installing_deps.sh.

The LEVEL_DB_DATA folder contains a 2018 folder but no 2017, and I get this error in `screen -r Script`:
```
Traceback (most recent call last):
  File "./Duplicates.py", line 118, in <module>
    for dico_hash in curr_dico_redis.smembers('HASHS_'+hash_type):
  File "/opt/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/client.py", line 1638, in smembers
    return self.execute_command('SMEMBERS', name)
  File "/opt/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/opt/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/opt/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:2017. Connection refused.
```

**Comment by mokaddem** [comment]
Hi,
Manually create the directory ``2017`` in ``/LEVEL_DB_DATA/`` should solve this issue (or at least this error). Can you confirm?

**Comment by mokaddem** [comment]
#178 Should cover this issue.

**Comment by jeromeleonard** [comment]
creating manually the `/LEVEL_DB_DATA/2017` makes the script starting successfully. thx.
