### ISSUE TITLE
Pressing <ENTER> does not start the manager

### ISSUE THREAD

**Issue by jeromeleonard** [CIRCL/AIL-framework#177]
OS: Ubuntu 16.04
installation: git clone and installing_deps.sh
Client: MacOS and Terminal.app

I get the following error when I enter screen with `screen -r Script`, navigate to the next panel (C-n) and press <ENTER>: 

```
Press < ENTER > to launch the manager...
Traceback (most recent call last):
  File "./ModulesInformationV2.py", line 837, in <module>
    Screen.wrapper(demo)
  File "/opt/AIL-framework/AILENV/local/lib/python2.7/site-packages/asciimatics/screen.py", line 1169, in wrapper
    func(screen)
  File "./ModulesInformationV2.py", line 740, in demo
    dashboard = Dashboard(screen)
  File "./ModulesInformationV2.py", line 255, in __init__
    self.fix()
  File "/opt/AIL-framework/AILENV/local/lib/python2.7/site-packages/asciimatics/widgets.py", line 320, in fix
    y = layout.fix(x, y, width, height)
  File "/opt/AIL-framework/AILENV/local/lib/python2.7/site-packages/asciimatics/widgets.py", line 923, in fix
    h = widget.required_height(offset, w)
  File "/opt/AIL-framework/AILENV/local/lib/python2.7/site-packages/asciimatics/widgets.py", line 1498, in required_height
    return self._required_height
AttributeError: 'CLabel' object has no attribute '_required_height'
```

In the screen, I also noticed that I do not have the status bar like in the pdf presentation.

**Comment by mokaddem** [comment]
Hi,
#179 should solve the issue. 
Can you confirm that it works on your side?
Thanks

**Comment by Terrtia** [comment]
It should be fixed in the recent version of AIL. Feel free to reopen if this is not case.
