### ISSUE TITLE
Bug in Categ.py

### ISSUE THREAD

**Issue by mokaddem** [CIRCL/AIL-framework#200]
Traceback (most recent call last):
  File "./Categ.py", line 98, in <module>
    found = set(re.findall(pattern, content))
  File "/home/ail/git/AIL-framework/AILENV/lib/python3.5/re.py", line 213, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by mokaddem** [comment]
Also, on ``Web.py``

**Comment by Terrtia** [comment]
Type Error should be fix with d7ba5533be65bb6f811765520c8383f1d9e942ba
