### ISSUE TITLE
docker is still using redis for 6382 but config is for ardb

### ISSUE THREAD

**Issue by obilodeau** [CIRCL/AIL-framework#209]
```
$ docker run -p 7000:7000 ail-framework
Misp not connected
The HIVE not connected
Traceback (most recent call last):
  File "/opt/AIL/AILENV/lib/python3.5/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/opt/AIL/AILENV/lib/python3.5/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/opt/AIL/AILENV/lib/python3.5/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/AIL/AILENV/lib/python3.5/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/opt/AIL/AILENV/lib/python3.5/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/AIL/AILENV/lib/python3.5/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/opt/AIL/AILENV/lib/python3.5/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6382. Cannot assign requested address.
```

`LAUNCH.sh` (not used by docker setup) launches `ardb` on 6382 but `docker_start.sh` launches redis. The config file for 6382 uses a `home` statement that is incompatible with redis so the server doesn't start. This prevents the rest to start.

I don't know how you want to fix this so I'm just reporting but I have other docker fixes coming soon.

**Comment by obilodeau** [comment]
This problem happens after patches for #210 and #211 have been applied. I'm going to submit what I did to fix this problem.
