### ISSUE TITLE
ARDB connection issue

### ISSUE THREAD

**Issue by incert** [CIRCL/AIL-framework#224]
Hi,

after installing  AiL, I could launch Redis, Ardb, logs, Queues properly.
Scripts  however fail to start:

```
Scripts was checked
Check an option (again to uncheck, ENTER when done):
Could not connect to Redis at 127.0.0.1:6382: Connection refused
        6382 not ready
        Script not started, waiting 5 secondes
Could not connect to Redis at 127.0.0.1:6382: Connection refused
        6382 not ready
        Script not started
```

I tried to edit Redis config file to make it listen on port 6382, but after restart, it still listen on 6379, 6380 and 6381.

My question is how to force redis to start listening on 6382 (without weird iptables rerouting rules), or where can I configure scripts to target redis on port 6379?

**Comment by Terrtia** [comment]
Hi icert !

you don't need any rerouting rules
6382 is Ardb, he need some time to be launched.

You just need to launch all the scripts when ardb is fully launched.
(you can check ardb status in the `ARDB_AIL` screen.)

**Comment by incert** [comment]
Terrtia, 

right, at least I can access the different screen to see what is going on, thx for the hint.

ARDB is started:
```
[1051] 07-10 14:00:41,422 INFO Ardb init engine:rocksdb success.
[1051] 07-10 14:00:41,454 INFO Ardb will accept connections on 127.0.0.1:6382
[1051] 07-10 14:00:41,455 INFO Ardb started with version 0.10.0
```
But netstat -tulpn do not show anything listening on localhost:6382 (only SSH, the tor package, python on 2 ports, and the 3 redis server).
the only logs I can find with alerts is the following in the Queue screen:
```
alertHandler has no publisher.
misp_the_hive_feeder has no publisher.
SentimentAnalysis has no publisher.
Release has no publisher.
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 786, in get
    value = d[option]
  File "/home/cg/AIL-framework/AILENV/lib/python3.5/collections/__init__.py", line 881, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/home/cg/AIL-framework/AILENV/lib/python3.5/collections/__init__.py", line 873, in __missing__
    raise KeyError(key)
KeyError: 'subscribe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./QueueIn.py", line 24, in <module>
    run(args.config_section)
  File "./QueueIn.py", line 12, in run
    p.populate_set_in()
  File "/home/cg/AIL-framework/bin/Helper.py", line 142, in populate_set_in
    src = self.modules.get(self.subscriber_name, 'subscribe')
  File "/usr/lib/python3.5/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'subscribe' in section: 'submit_paste'
Indexer output queue finished.
SentimentAnalysis output queue finished.
Duplicates output queue finished.
ModuleStats output queue finished.
WebStats output queue finished.
DumpValidOnion output queue finished.
RegexForTermsFrequency output queue finished.
Release output queue finished.
misp_the_hive_feeder output queue finished.
submit_paste input queue finished.
DomClassifier output queue finished.
CurveManageTopSets output queue finished.
alertHandler output queue finished.
SetForTermsFrequency output queue finished.
Attributes output queue finished.
```

any idea?

**Comment by znb** [comment]
This came up for me today. It seems the redis instance for Ardb is crashing on my instance...

```
[3971] 07-17 17:17:21,230 INFO [RocksDB]EVENT_LOG_v1 {"time_micros": 1531844241230183, "job": 1, "event": "recovery_finished"}
[3971] 07-17 17:17:21,234 INFO [RocksDB][db/db_impl_open.cc:1188] DB pointer 0x7f3ee4f8c000
[3971] 07-17 17:17:21,234 INFO RocksDB open column family:default success.
[3971] 07-17 17:17:21,234 INFO Ardb init engine:rocksdb success.
[3971] 07-17 17:17:21,236 INFO Ardb will accept connections on 127.0.0.1:6382
[3971] 07-17 17:17:21,236 INFO Ardb started with version 0.10.0
bash: line 1:  3971 Aborted                 (core dumped) ardb-server /opt/AIL-framework/configs/6382.conf
```

Running on Ubuntu 16.04.

Let me know if you need any more information.

**Comment by incert** [comment]
I confirm I do have the same "aborted" error when scripts are started; and I do use a Debian 9.4

**Comment by Terrtia** [comment]
Hi,

Did you change the ardb config file `configs/6382.conf` ?

The core dump seem to be an Ardb issue, 
I can't really fix an Ardb core dump,
You should maybe open an issue on [Ardb](https://github.com/yinqiwen/ardb)

**Comment by Terrtia** [comment]
Currently loglevel is set to info, can you please set it to debug or trace and give me the output ?

configs/6382.conf:
```configs/6382.conf
# Specify the server verbosity level.
# This can be one of:
# error
# warn
# info 
# debug
# trace
loglevel debug
```

**Comment by incert** [comment]
log output with debug settings:

```
[7233] 07-18 13:39:32,943 INFO Ardb will accept connections on 127.0.0.1:6382
[7233] 07-18 13:39:32,944 INFO Ardb started with version 0.10.0
[7233] 07-18 13:40:00,964 INFO ========================Period Statistics Dump Begin===========================
[7233] 07-18 13:40:00,964 INFO slave_sync_total_commands_processed:0
[7233] 07-18 13:40:00,964 INFO slave_sync_instantaneous_ops_per_sec:0
[7233] 07-18 13:40:00,964 INFO total_commands_processed:0
[7233] 07-18 13:40:00,964 INFO instantaneous_ops_per_sec:0
[7233] 07-18 13:40:00,964 INFO total_connections_received:0
[7233] 07-18 13:40:00,964 INFO rejected_connections:0
[7233] 07-18 13:40:00,964 INFO ========================Period Statistics Dump End===========================
[7233] 07-18 13:44:52,165 DEBUG Inherit pipeline initializor from server socket.
[7233] 07-18 13:44:52,165 DEBUG Inherit pipeline finalizer from server socket.
[7233] 07-18 13:44:52,165 DEBUG Server channel(66) Accept a client channel(289) for fd:34
[7233] 07-18 13:44:52,165 DEBUG Process recved cmd:ping
[7233] 07-18 13:44:52,165 DEBUG Process recved cmd cost 3us
bash: line 1:  7233 Aborted                 ardb-server /home/cg/AIL-framework/configs/6382.conf

```

**Comment by Terrtia** [comment]
@sw-pschmied pointed an interesting workaround on  #226 

Can you try it ?

**Comment by incert** [comment]
I change the 6382.conf file and issue remains:
```
[8117] 07-18 15:20:46,731 INFO Ardb init engine:rocksdb success.
[8117] 07-18 15:20:46,733 INFO Ardb will accept connections on 127.0.0.1:6382
[8117] 07-18 15:20:46,734 INFO Ardb started with version 0.10.0
[8117] 07-18 15:26:14,109 DEBUG Inherit pipeline initializor from server socket.
[8117] 07-18 15:26:14,109 DEBUG Inherit pipeline finalizer from server socket.
[8117] 07-18 15:26:14,109 DEBUG Server channel(66) Accept a client channel(289) for fd:34
[8117] 07-18 15:26:14,110 DEBUG Process recved cmd:ping
[8117] 07-18 15:26:14,110 DEBUG Process recved cmd cost 4us
bash: line 1:  8117 Aborted                 ardb-server /home/cg/AIL-framework/configs/6382.conf

```

**Comment by adulau** [comment]
This could be related to a file-system not supporting direct IO. 

https://github.com/CIRCL/AIL-framework#installation-notes

Could you disable it in the ardb configuration? and see if this solves your issue. Thank you.

**Comment by incert** [comment]
in 6382.conf:

```
#rocksdb's options
rocksdb.options               write_buffer_size=512M;max_write_buffer_number=5;min_write_buffer_number_to_merge=3;compression=kSnappyCompression;\
                              bloom_locality=1;memtable_prefix_bloom_size_ratio=0.1;\
                              block_based_table_factory={block_cache=512M;filter_policy=bloomfilter:10:true};\
                              create_if_missing=true;max_open_files=10000;rate_limiter_bytes_per_sec=50M;\
                              use_direct_io_for_flush_and_compaction=false;use_adaptive_mutex=true

#leveldb's options
leveldb.options               block_cache_size=512M,write_buffer_size=128M,max_open_files=5000,block_size=4k,block_restart_interval=16,\
                              bloom_bits=10,compression=snappy,logenable=yes,max_file_size=2M
```
in ARDB logs, I do not see the error anymore when launching the scripts:
```
[11146] 07-23 07:56:18,797 INFO RocksDB open column family:default success.
[11146] 07-23 07:56:18,797 INFO Ardb init engine:rocksdb success.
[11146] 07-23 07:56:18,799 INFO Ardb will accept connections on 127.0.0.1:6382
[11146] 07-23 07:56:18,800 INFO Ardb started with version 0.10.0
```
yet the script startup still fail:
```
What do you want to Launch?:
  1 ) Redis
  2 ) Ardb
  3 ) Logs
  4 ) Queues
  5+) Scripts
  6 ) Killall
  7 ) Shutdown
  8 ) Update-config
  9 ) Update-thirdparty
Scripts was checked
Check an option (again to uncheck, ENTER when done):
Error: Server closed the connection
        6382 not ready
        Script not started, waiting 5 secondes
Could not connect to Redis at 127.0.0.1:6382: Connection refused
        6382 not ready
        Script not started
```
I just noticed that when I launch the LAUNCH.sh script, I have this message: does it implies I need to update some dependencies location?
```
    This script launch:

    - All the ZMQ queuing modules.
    - All the ZMQ processing modules.
    - All Redis in memory servers.
    - All Level-DB on disk servers.

    (Inside screen Daemons)

    But first of all you'll need to edit few path where you installed
    your redis & ardb servers.
```

**Comment by SteveClement** [comment]
Dear all

We have reproduced the issue on a VM and are investigating it.

**Comment by incert** [comment]
thanks, let me know if anything else is required or if you need further tests

**Comment by mokaddem** [comment]
From what I understand, you do not longer have the ``core dumped`` message in ARDB.
We recently updated the ``LAUNCHER.py`` to wait until the ARDB server is ready, instead of a simple exit.
Could you try to pull the latest changes and start the launcher with the ``-y`` option (ARDB can take some time to load).
And, by the way, there is a free [AIL training](https://en.xing-events.com/QTINGZX.html) in Luxembourg on the 3rd of September. If you need more help or want to learn how to create non-existing feature in AIL, you are more than welcome.

**Comment by znb** [comment]
@mokaddem  There is no LAUNCHER.py script in my source folder and the LAUNCHER.sh file does not take a -y option.

Please advise.

**Comment by mokaddem** [comment]
You are right, the script name is ``LAUNCH.sh`` and is located in [``bin/LAUNCH.sh``](https://github.com/CIRCL/AIL-framework/blob/master/bin/LAUNCH.sh)

**Comment by incert** [comment]
LAUNCH.sh should be run inside python virtual environment, yet the command to activate it does not work anymore, the AILENV folder have disappear and I cannot find it elsewhere it in my installation folder.

**Comment by incert** [comment]
I also tried the docker install in the mean time, but when docker build the container, I got multiples errors along the process (even if it finished with build success). So what can I do for this AILENV issue?

**Comment by incert** [comment]
ok my bad, I forget this step when reinstalling it.

it seems to works better:
```
$ ./LAUNCH.sh -l
        * Launching Redis servers
        * Launching ARDB servers
        * Launching logging process
        * Launching all the queues
        * Checking configuration
        * Configuration up-to-date
        * Launching ZMQ scripts
        * Launching Flask server
$ screen -list
There are screens on:
        26923.Flask_AIL (09/04/2018 09:54:17 AM)        (Detached)
        26515.Script_AIL        (09/04/2018 09:54:13 AM)        (Detached)
        26330.Queue_AIL (09/04/2018 09:54:10 AM)        (Detached)
        26283.Logging_AIL       (09/04/2018 09:54:10 AM)        (Detached)
        26269.ARDB_AIL  (09/04/2018 09:54:10 AM)        (Detached)
        26246.Redis_AIL (09/04/2018 09:54:09 AM)        (Detached)
6 Sockets in /run/screen/S-user.
```
I'll continue the process, thanks

**Comment by incert** [comment]
I could acces web interface, and everything seems ok now, so thanks for the new LAUNCH script !
