### ISSUE TITLE
problem with pystemon-feeder

### ISSUE THREAD

**Issue by krishah** [CIRCL/AIL-framework#234]
Hello
I have problem with pystemon-feeder (checked in two machines ubuntu 16.04)
AIL works fine, pystemon too ( I hope) but when I started pystemon feeder get problem with unicode strings
```
(AILENV) root@threat:/opt/AIL-framework/bin/feeder# ./pystemon-feeder.py
archive/slexy.org/2018/08/13/s212wDo309.gz
Traceback (most recent call last):
  File "./pystemon-feeder.py", line 65, in <module>
    socket.send("%d %s" % (topic, paste))
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/zmq/sugar/socket.py", line 392, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 725, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 769, in zmq.backend.cython.socket.Socket.send
TypeError: unicode not allowed, use send_string
```
script import_dit_py works fine.

**Comment by Terrtia** [comment]
Hi @krishah !

Thank for the report !

Should be fix with 6f2dbcb4e27e97597a3bf05ee529468b68dc0375,
Can you please confirm ?

**Comment by krishah** [comment]
i confirm - works fine.
Thank You for your quick response.

**Comment by krishah** [comment]
Probably same source of problem with Flask.sh


```
root@threat:/opt/AIL-framework/var/www# ./Flask_server.py
Misp not connected
The HIVE not connected
Traceback (most recent call last):
  File "./Flask_server.py", line 66, in <module>
    importlib.import_module(name)
  File "/opt/AIL-framework/AILENV/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "modules/Tags/Flask_Tags.py", line 34, in <module>
    clusters = Clusters(skip_duplicates=True)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/pymispgalaxies/api.py", line 272, in __init__
    clusters.append(json.load(f))
  File "/usr/lib/python3.5/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/opt/AIL-framework/AILENV/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 479: ordinal not in range(128)
```

**Comment by Terrtia** [comment]
Can you please do an update third-party ? (check the 10 option in `/bin/LAUNCH.sh`)
