### ISSUE TITLE
Stuck queues using import_dir.py/ ModulesInformationV2.py autokill crash

### ISSUE THREAD

**Issue by terrieristorg** [CIRCL/AIL-framework#244]
I'm having trouble it seems with queues getting stuck. I use my own paste scraper and was running import_dir.py once daily but the next day it would show it imported all the files (output of import_dir.py) but no new pastes showed up under "important pastes" etc. I also tried running the import script hourly to the same effect. It does import some pastes, but at some point gets stuck. I tried running ModulesInformationv2.py with autokill enabled but get the error:

`Traceback (most recent call last):
  File "./ModulesInformationV2.py", line 848, in <module>
    Screen.wrapper(demo)
  File "/root/AIL-framework/AILENV/lib/python3.5/site-packages/asciimatics/screen.py", line 1169, in wrapper
    func(screen)
  File "./ModulesInformationV2.py", line 775, in demo
    TABLES["logs"] = format_string(printarrayLog, TABLES_PADDING["logs"])
  File "./ModulesInformationV2.py", line 727, in format_string
    if len(elem) > padding_row[ite]:
TypeError: object of type 'NoneType' has no len()`

Attached are pictures of the queues. Not sure where else to check for tracebacks to find where the error is occurring. Please advise on any troubleshooting/how to proceed. Thank you!

![screen shot 2018-09-05 at 1 44 08 pm](https://user-images.githubusercontent.com/42216039/45112875-e558d080-b116-11e8-8eaf-30d798e74112.png)
![screen shot 2018-09-05 at 1 43 00 pm](https://user-images.githubusercontent.com/42216039/45112884-ebe74800-b116-11e8-9c84-a4e9f3f506ad.png)
![screen shot 2018-09-05 at 1 43 39 pm](https://user-images.githubusercontent.com/42216039/45112885-ec7fde80-b116-11e8-892e-dd6f6a3a63c6.png)

**Comment by Terrtia** [comment]
Hello,

You should have output for the script screen. Did you navigate through windows? slide 38 of [this presentation](https://github.com/CIRCL/AIL-framework/blob/master/doc/presentation/ail-training-november.pdf) shows useful commands.
Especially, what is the output of the ``Mixer.py`` script (second window)?

You can test manually the tagging system. You just need to paste something on the Paste Submit tab.
-----BEGIN CERTIFICATE-----
aaaaaaaaaaaaaaaaaaaaaaaaaa
-----END CERTIFICATE-----
This should be detected as certificate.

**Comment by terrieristorg** [comment]
I think I've found where the error is occurring. I  "fixed" a bug in the code which in turn created the problems, so maybe you can help with fixing the original code:

The original problem is in import_dir.py on a fresh install, running in AILENV:
`Traceback (most recent call last):
  File "./import_dir.py", line 89, in <module>
    out = StringIO.StringIO()
AttributeError: type object '_io.StringIO' has no attribute 'StringIO'
 `

I tried changing StringIO.StringIO() to just StringIO() hoping to make it compliant with python 3, resulting in 

`Traceback (most recent call last):
  File "./import_dir.py", line 90, in <module>
    with gzip.GzipFile(fileobj=out, mode="w") as f:
  File "/usr/lib/python3.5/gzip.py", line 192, in __init__
    self._write_gzip_header()
  File "/usr/lib/python3.5/gzip.py", line 220, in _write_gzip_header
    self.fileobj.write(b'\037\213')             # magic header
TypeError: string argument expected, got 'bytes'`

So I changed line 6 of import_dir.py to
`from io import BytesIO`

and line 89 to:
`out = BytesIO()`

That seemed to work fine except I'm guessing it is finding a paste with an invalid character and I get tracebacks such as:
`Traceback (most recent call last):
  File "./Lines.py", line 66, in <module>
    PST = Paste.Paste(message)
  File "/root/AIL-framework/bin/packages/Paste.py", line 89, in __init__
    self.p_mime = magic.from_buffer(self.get_p_content(), mime=True)
  File "/root/AIL-framework/bin/packages/Paste.py", line 120, in get_p_content
    paste = self.cache.get(self.p_path)
  File "/root/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 976, in get
    return self.execute_command('GET', name)
  File "/root/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/root/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/root/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/root/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 326, in read_response
    response = self.encoder.decode(response)
  File "/root/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 125, in decode
    value = value.decode(self.encoding, self.encoding_errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 13: invalid start byte`

and this:

`Traceback (most recent call last):
  File "./DomClassifier.py", line 69, in <module>
    main()
  File "./DomClassifier.py", line 46, in main
    paste = PST.get_p_content()
  File "/root/AIL-framework/bin/packages/Paste.py", line 120, in get_p_content
    paste = self.cache.get(self.p_path)
  File "/root/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 976, in get
    return self.execute_command('GET', name)
  File "/root/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/root/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/root/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/root/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 326, in read_response
    response = self.encoder.decode(response)
  File "/root/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 125, in decode
    value = value.decode(self.encoding, self.encoding_errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 14: invalid start byte`

This is where the queues are crashing. Is there something else I can replace StringIO.StringIO() in import_dir.py with? Thank you again and any help is appreciated.

**Comment by kovacsbalu** [comment]
Hi @Terrtiam I have similar issue with UnicodeDecodeError. 
But I got this in modules (categ, indexer, lines, base64...).
Maybe the root cause in Paste.py line 120 ?
```Traceback (most recent call last):
  File "./Categ.py", line 89, in <module>
    paste = Paste.Paste(filename)
  File "/opt/AIL/bin/packages/Paste.py", line 89, in __init__
    self.p_mime = magic.from_buffer(self.get_p_content(), mime=True)
  File "/opt/AIL/bin/packages/Paste.py", line 120, in get_p_content
    paste = self.cache.get(self.p_path)
  File "/opt/AIL/AILENV/lib/python3.5/site-packages/redis/client.py", line 976, in get
    return self.execute_command('GET', name)
  File "/opt/AIL/AILENV/lib/python3.5/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/AIL/AILENV/lib/python3.5/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/opt/AIL/AILENV/lib/python3.5/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/opt/AIL/AILENV/lib/python3.5/site-packages/redis/connection.py", line 326, in read_response
    response = self.encoder.decode(response)
  File "/opt/AIL/AILENV/lib/python3.5/site-packages/redis/connection.py", line 125, in decode
    value = value.decode(self.encoding, self.encoding_errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 15: invalid continuation byte```

**Comment by Terrtia** [comment]
hey @kovacsbalu 

This should be fix with b575efcc4683954452b09c8463dd32c7b0a2cda3

Can you please try it ?

If this doesn't work, can you please open a new issue ?

**Comment by kovacsbalu** [comment]
Hi @Terrtia, unfortunately this fix has other problems...
```
s = b' '.join( [ topic.encode(), path_to_send.encode(), base64.b64encode(messagedata) ] )
AttributeError: 'int' object has no attribute 'encode'
```
I tried to fix with `bytes(topic)` but, there is no paste in queue.

**Comment by kovacsbalu** [comment]
@Terrtia, looks good. Let's run for some day :)
