### ISSUE TITLE
Crash when opening monitor

### ISSUE THREAD

**Issue by FafnerKeyZee** [CIRCL/AIL-framework#268]
With a fresh git pull from this morning:

> Traceback (most recent call last):
  File "./ModulesInformationV2.py", line 850, in <module>
    Screen.wrapper(demo)
  File "/home/fafner/AIL-framework/AILENV/lib/python3.5/site-packages/asciimatics/screen.py", line 1170, in wrapper
    return func(screen)
  File "./ModulesInformationV2.py", line 759, in demo
    Scene([confirm], -1, name="confirm"),
  File "/home/fafner/AIL-framework/AILENV/lib/python3.5/site-packages/asciimatics/scene.py", line 32, in __init__
    self.add_effect(effect)
  File "/home/fafner/AIL-framework/AILENV/lib/python3.5/site-packages/asciimatics/scene.py", line 84, in add_effect
    effect.reset()
  File "/home/fafner/AIL-framework/AILENV/lib/python3.5/site-packages/asciimatics/widgets.py", line 694, in reset
    self._on_load()
  File "./ModulesInformationV2.py", line 319, in _setValue
    action = current_selected_action + " " + str(current_selected_amount) + "x"
TypeError: unsupported operand type(s) for +: 'int' and 'str'

Best regards,

**Comment by timhux123** [comment]
Seeing the same here. I performed a git pull last week and ran "./ModulesInformationV2.py" today and received the same error.

**Comment by xme** [comment]
Same error here. I tried to fix it. Then I got another error, then another one, etc... What is broken?

**Comment by xme** [comment]
Any news about this issue?

**Comment by Terrtia** [comment]
Fixed
