### ISSUE TITLE
Multiple queue error

### ISSUE THREAD

**Issue by v0ris** [CIRCL/AIL-framework#294]
Dear team!
I have run the python3_upgrade.sh script, and then some scripts going to stuck. Error messages:

./SentimentAnalysis.py
Dropped: text/x-c
ideone.com_1543302000 -> 61996 dropped 1 lines
Traceback (most recent call last):
  File "./SentimentAnalysis.py", line 168, in <module>
    Analyse(message, server)
  File "./SentimentAnalysis.py", line 114, in Analyse
    server.set(UniqID, avg_score)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 1394, in set
    return self.execute_command('SET', *pieces)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 754, in execute_command
    connection.send_command(*args)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 659, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 124, in encode
    "byte, string or number first." % typename)
redis.exceptions.DataError: Invalid input of type: 'dict'. Convert to a byte, string or number first.

./ModuleStats.py
Traceback (most recent call last):
  File "./ModuleStats.py", line 163, in <module>
    compute_provider_info(r_serv_trend, r_serv_pasteName, message)
  File "./ModuleStats.py", line 90, in compute_provider_info
    server_trend.zadd(redis_sum_size_set, float(num_paste), paste_provider)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/_compat.py", line 123, in iteritems
    return iter(x.items())
AttributeError: 'float' object has no attribute 'items'

./Duplicates.py
Traceback (most recent call last):
  File "./Duplicates.py", line 156, in <module>
    r_serv1.set(index+'_date', PST._get_p_date())
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 1394, in set
    return self.execute_command('SET', *pieces)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 754, in execute_command
    connection.send_command(*args)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 659, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 124, in encode
    "byte, string or number first." % typename)
redis.exceptions.DataError: Invalid input of type: 'Date'. Convert to a byte, string or number first.

./Curve.py
Traceback (most recent call last):
  File "./Curve.py", line 157, in <module>
    server_term.zincrby(curr_set, low_word, float(score))
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 2281, in zincrby
    return self.execute_command('ZINCRBY', name, amount, value)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 755, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 768, in parse_response
    response = connection.read_response()
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 638, in read_response
    raise response
redis.exceptions.ResponseError: value is not a valid float or out of range

./Decoder.py
base64
b009399cefaa0e82086453da04a887105ca2f6a4
Traceback (most recent call last):
  File "./Decoder.py", line 238, in <module>
    content = decode_string(content, message, date, encoded_list, decoder['name'], decoder['encoded_min_size'])
  File "./Decoder.py", line 50, in decode_string
    save_hash(decoder_name, message, date, decode)
  File "./Decoder.py", line 78, in save_hash
    serv_metadata.zincrby('hash_date:'+date_key, hash, 1)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 2281, in zincrby
    return self.execute_command('ZINCRBY', name, amount, value)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 755, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 768, in parse_response
    response = connection.read_response()
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/connection.py", line 638, in read_response
    raise response
redis.exceptions.ResponseError: value is not a valid float or out of range

./WebStats.py
added in domain_set_201811: w3.org
Traceback (most recent call last):
  File "./WebStats.py", line 186, in <module>
    compute_progression(r_serv_trend, 'scheme', num_day_to_look, url_parsed)
  File "./WebStats.py", line 95, in compute_progression
    server.zadd(redis_progression_name_set, float(keyword_increase), keyword)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/redis/_compat.py", line 123, in iteritems
    return iter(x.items())
AttributeError: 'float' object has no attribute 'items'

**Comment by Terrtia** [comment]
hey @v0ris,

This seem to be a redis or an ardb issue.
Can you please check if you find any error in the Redis_AIL or ARDB_AIL screen ?

**Comment by v0ris** [comment]
I do not find any error in the screens:
I have tried reinstall the AIL-Fraemwork also but I have the same issue.

[8643] 11-27 10:20:00,262 INFO slave_sync_instantaneous_ops_per_sec:0
[8643] 11-27 10:20:00,262 INFO total_commands_processed:3550088
[8643] 11-27 10:20:00,262 INFO instantaneous_ops_per_sec:0
[8643] 11-27 10:20:00,262 INFO total_connections_received:72
[8643] 11-27 10:20:00,262 INFO rejected_connections:0
[8643] 11-27 10:20:00,262 INFO ========================Period Statistics Dump End===========================
[8643] 11-27 10:30:00,655 INFO ========================Period Statistics Dump Begin===========================
[8643] 11-27 10:30:00,655 INFO coststat_scard_all:calls=202,costs=8423,cost_per_call=41,percents=100.0000%
[8643] 11-27 10:30:00,655 INFO coststat_scard_range[0-1000]:calls=202,costs=8423,cost_per_call=41,percents=100.0000%
[8643] 11-27 10:30:00,655 INFO coststat_zrange_all:calls=8,costs=94,cost_per_call=11,percents=100.0000%
[8643] 11-27 10:30:00,655 INFO coststat_zrange_range[0-1000]:calls=8,costs=94,cost_per_call=11,percents=100.0000%
[8643] 11-27 10:30:00,655 INFO coststat_zrevrangebyscore_all:calls=124,costs=1584,cost_per_call=12,percents=100.0000%
[8643] 11-27 10:30:00,655 INFO coststat_zrevrangebyscore_range[0-1000]:calls=124,costs=1584,cost_per_call=12,percents=100.0000%
[8643] 11-27 10:30:00,655 INFO slave_sync_total_commands_processed:0
[8643] 11-27 10:30:00,655 INFO slave_sync_instantaneous_ops_per_sec:0
[8643] 11-27 10:30:00,655 INFO total_commands_processed:3550422
[8643] 11-27 10:30:00,655 INFO instantaneous_ops_per_sec:0
[8643] 11-27 10:30:00,655 INFO total_connections_received:72
[8643] 11-27 10:30:00,655 INFO rejected_connections:0
[8643] 11-27 10:30:00,655 INFO ========================Period Statistics Dump End===========================
[8643] 11-27 10:40:00,043 INFO ========================Period Statistics Dump Begin===========================
[8643] 11-27 10:40:00,043 INFO coststat_scard_all:calls=202,costs=8148,cost_per_call=40,percents=100.0000%
[8643] 11-27 10:40:00,043 INFO coststat_scard_range[0-1000]:calls=202,costs=8148,cost_per_call=40,percents=100.0000%
[8643] 11-27 10:40:00,043 INFO coststat_zrange_all:calls=8,costs=71,cost_per_call=8,percents=100.0000%
[8643] 11-27 10:40:00,043 INFO coststat_zrange_range[0-1000]:calls=8,costs=71,cost_per_call=8,percents=100.0000%
[8643] 11-27 10:40:00,043 INFO coststat_zrevrangebyscore_all:calls=124,costs=1623,cost_per_call=13,percents=100.0000%
[8643] 11-27 10:40:00,043 INFO coststat_zrevrangebyscore_range[0-1000]:calls=124,costs=1623,cost_per_call=13,percents=100.0000%
[8643] 11-27 10:40:00,043 INFO slave_sync_total_commands_processed:0
[8643] 11-27 10:40:00,043 INFO slave_sync_instantaneous_ops_per_sec:0
[8643] 11-27 10:40:00,043 INFO total_commands_processed:3550756
[8643] 11-27 10:40:00,043 INFO instantaneous_ops_per_sec:0
[8643] 11-27 10:40:00,043 INFO total_connections_received:72
[8643] 11-27 10:40:00,043 INFO rejected_connections:0
[8643] 11-27 10:40:00,043 INFO ========================Period Statistics Dump End===========================
[8643] 11-27 10:50:00,424 INFO ========================Period Statistics Dump Begin===========================
[8643] 11-27 10:50:00,424 INFO coststat_scard_all:calls=202,costs=8874,cost_per_call=43,percents=100.0000%
[8643] 11-27 10:50:00,424 INFO coststat_scard_range[0-1000]:calls=202,costs=8874,cost_per_call=43,percents=100.0000%
[8643] 11-27 10:50:00,424 INFO coststat_zrange_all:calls=8,costs=69,cost_per_call=8,percents=100.0000%
[8643] 11-27 10:50:00,424 INFO coststat_zrange_range[0-1000]:calls=8,costs=69,cost_per_call=8,percents=100.0000%
[8643] 11-27 10:50:00,424 INFO coststat_zrevrangebyscore_all:calls=124,costs=1330,cost_per_call=10,percents=100.0000%
[8643] 11-27 10:50:00,424 INFO coststat_zrevrangebyscore_range[0-1000]:calls=124,costs=1330,cost_per_call=10,percents=100.0000%
[8643] 11-27 10:50:00,424 INFO slave_sync_total_commands_processed:0
[8643] 11-27 10:50:00,424 INFO slave_sync_instantaneous_ops_per_sec:0
[8643] 11-27 10:50:00,424 INFO total_commands_processed:3551090
[8643] 11-27 10:50:00,424 INFO instantaneous_ops_per_sec:0
[8643] 11-27 10:50:00,424 INFO total_connections_received:72
[8643] 11-27 10:50:00,424 INFO rejected_connections:0
[8643] 11-27 10:50:00,424 INFO ========================Period Statistics Dump End===========================
[8643] 11-27 11:00:00,822 INFO ========================Period Statistics Dump Begin===========================
[8643] 11-27 11:00:00,822 INFO coststat_scard_all:calls=202,costs=9009,cost_per_call=44,percents=100.0000%
[8643] 11-27 11:00:00,822 INFO coststat_scard_range[0-1000]:calls=202,costs=9009,cost_per_call=44,percents=100.0000%
[8643] 11-27 11:00:00,822 INFO coststat_zrange_all:calls=8,costs=63,cost_per_call=7,percents=100.0000%
[8643] 11-27 11:00:00,822 INFO coststat_zrange_range[0-1000]:calls=8,costs=63,cost_per_call=7,percents=100.0000%
[8643] 11-27 11:00:00,822 INFO coststat_zrevrangebyscore_all:calls=124,costs=1504,cost_per_call=12,percents=100.0000%
[8643] 11-27 11:00:00,822 INFO coststat_zrevrangebyscore_range[0-1000]:calls=124,costs=1504,cost_per_call=12,percents=100.0000%
[8643] 11-27 11:00:00,822 INFO slave_sync_total_commands_processed:0
[8643] 11-27 11:00:00,822 INFO slave_sync_instantaneous_ops_per_sec:0
[8643] 11-27 11:00:00,822 INFO total_commands_processed:3551424
[8643] 11-27 11:00:00,822 INFO instantaneous_ops_per_sec:0
[8643] 11-27 11:00:00,822 INFO total_connections_received:72
[8643] 11-27 11:00:00,822 INFO rejected_connections:0
[8643] 11-27 11:00:00,822 INFO ========================Period Statistics Dump End===========================


18651:M 27 Nov 11:08:43.776 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
18651:M 27 Nov 11:08:43.776 # Server started, Redis version 3.2.12
18651:M 27 Nov 11:08:43.776 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
18651:M 27 Nov 11:08:43.776 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
18651:M 27 Nov 11:08:43.776 * The server is now ready to accept connections on port 6381

**Comment by Terrtia** [comment]
> The server is now ready to accept connections on port 6381

Did you change the default configuration ? ARDB should run on 6382 by default.

**Comment by mokaddem** [comment]
Hi,
This may not solve all of your issues but it will be a good start.

According to https://github.com/andymccurdy/redis-py#zincrby , they swapped the value and the amount for the ``ZINCRBY`` command.

We should update the code to support redis-py-3.x.
In the mean time, you could quickly fix this with the following commands:
```
cd AIL-framework/ # Go the the folder where AIL is installed
sudo ./AILENV/bin/pip install --force-reinstall redis==2.10.6 # Re-install old version of redis-py (redis client)
```

**Comment by v0ris** [comment]
Dear mokaddem!

Thank you, currently the system work perfectly with this older redis client!
