### ISSUE TITLE
submit_paste.py crashes when reading paste containing hex listing

### ISSUE THREAD

**Issue by tr4cefl0w** [CIRCL/AIL-framework#339]
While working on a module to detect PE/ELF files in pastes (example here: https://pastebin.com/mVSvUxi0) I found that submit_paste.py crashes when attempting to read these files.

```
./submit_paste.py
Traceback (most recent call last):
  File "./submit_paste.py", line 238, in <module>
    content = f.read()
  File "/root/git/AIL-framework/AILENV/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
```

I have not explored any further but my guess is that there is some typecasting required to interpret the paste as a literal string. I will do additional tests when time allows and try to fix the issue if it has not been resolved.

**Comment by tr4cefl0w** [comment]
The issue came from PyMISPGalaxies due to the default locale in my Ubuntu 18.04 Docker container (the provided Docker build in the repository does not work for me) being en_US.UTF-8, which is pretty standard.

It's not necessarily PyMISPGalaxies' fault but more of a thing with Docker and Debian-based distributions. Read here: https://github.com/tianon/docker-brew-debian/issues/45

However, I'd suggest documenting this and precising that fresh installs in a Docker container should be done on a system using C.UTF-8 and not en_US.UTF-8
