### ISSUE TITLE
Indexer crash (due to gzip)

### ISSUE THREAD

**Issue by adulau** [CIRCL/AIL-framework#34]
Traceback (most recent call last):
  File "ZMQ_Sub_Indexer.py", line 59, in <module>
    PST = Paste.Paste(message.split(" ", -1)[-1])
  File "/home/adulau/AIL-framework/bin/packages/Paste.py", line 79, in **init**
    self.p_mime = magic.from_buffer(self.get_p_content(), mime=True)
  File "/home/adulau/AIL-framework/bin/packages/Paste.py", line 108, in get_p_content
    paste = f.read()
  File "/usr/lib/python2.7/gzip.py", line 254, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 325, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 343, in _read_eof
    crc32 = read32(self.fileobj)
  File "/usr/lib/python2.7/gzip.py", line 25, in read32
    return struct.unpack("<I", input.read(4))[0]
struct.error: unpack requires a string argument of length 4

**Comment by Terrtia** [comment]
fixed
