### ISSUE TITLE
Upgrade to 2.5 failed

### ISSUE THREAD

**Issue by xme** [CIRCL/AIL-framework#423]
```
# git ls-remote --tags
From https://github.com/CIRCL/AIL-framework.git
58355126313a195550b733117010853326aea23c	refs/tags/rm
edcfb4fcaa67462d3e004454d5dcc238d0a6889f	refs/tags/rm^{}
d54bade099fb91e276c357dae672be334838c4f5	refs/tags/v0.90
21f3a7c0575531cbfcd65dc9933d02c98073e9f7	refs/tags/v0.90^{}
236970fde8833a50601aa8e8c62db4e7343f5840	refs/tags/v1.0
36e79f2f30fe9e6384ac6c42e4c9113b475b2ffb	refs/tags/v1.0^{}
```
So, when I'm trying to re-launch:
```Traceback (most recent call last):
  File "/opt/AIL-framework//bin/Update.py", line 349, in <module>
    list_upper_tags_remote = get_git_upper_tags_remote(current_tag[1:], is_fork)
  File "/opt/AIL-framework//bin/Update.py", line 180, in get_git_upper_tags_remote
    if float(tag.split('^{}')[0][1:]) >= float(current_tag):
ValueError: could not convert string to float: 'm'
```

**Comment by xme** [comment]
Temporary fix for me:
```
if tag.split('^{}')[0][1:] != 'm' and float(tag.split('^{}')[0][1:]) >= float(current_tag):
```

**Comment by xme** [comment]
Now, I get this error on all pages (after successful authentication):

```

                                  ,d8       ,a8888a,     ad888888b,
                                ,d888     ,8P"'  `"Y8,  d8"     "88
                              ,d8" 88    ,8P        Y8,         a8P
                            ,d8"   88    88          88      aad8"
                          ,d8"     88    88          88      ""Y8,
                          8888888888888  `8b        d8'         "8b
                                   88     `8ba,  ,ad8'  Y8,     a88
                                   88       "Y8888P"     "Y888888P'

88888888888                       88           88           88           88
88                                88           ""           88           88
88                                88                        88           88
88aaaaa   ,adPPYba,   8b,dPPYba,  88,dPPYba,   88   ,adPPYb,88   ,adPPYb,88   ,adPPYba,  8b,dPPYba,
88"""""  a8"     "8a  88P'   "Y8  88P'    "8a  88  a8"    `Y88  a8"    `Y88  a8P_____88  88P'   `"8a
88       8b       d8  88          88       d8  88  8b       88  8b       88  8PP"""""""  88       88
88       "8a,   ,a8"  88          88b,   ,a8"  88  "8a,   ,d88  "8a,   ,d88  "8b,   ,aa  88       88
88        `"YbbdP"'   88          8Y"Ybbd8"'   88   `"8bbdP"Y8   `"8bbdP"Y8   `"Ybbd8"'  88       88
```

**Comment by Terrtia** [comment]
hey @xme !

We removed the ``rm`` tag

you need to relaunch the Update script (with ARDB and Redis running):
```bash
. ./AILENV/bin/activate
cd update/v2.5/
./Update.sh
```

**Comment by xme** [comment]
Fixed! Tx!

**Comment by Terrtia** [comment]
We added a new check in the Updater (to make sure it doesn't append anymore) bff9b45c26832815eb3086a80e25fae151ccc7a2
