### ISSUE TITLE
Internal Server Error while creating a Misp Event

### ISSUE THREAD

**Issue by petmi627** [CIRCL/AIL-framework#456]
Hi all,

I encountered a wired error then I wanted to open a misp event from a paste

On the page "PasteSubmit/create_misp_event" I received fallowing error message

`Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`

An in the Flask Screen I found this

```
[2020-01-22 08:53:27,646] ERROR in app: Exception on /PasteSubmit/create_misp_event [POST]
Traceback (most recent call last):
  File "/opt/ail-framework/AILENV/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/ail-framework/AILENV/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/ail-framework/AILENV/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/ail-framework/AILENV/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/ail-framework/AILENV/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/ail-framework/AILENV/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/ail-framework/AILENV/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./modules/Role_Manager.py", line 68, in decorated_view
    return func(*args, **kwargs)
  File "/opt/ail-framework//var/www/modules/PasteSubmit/Flask_PasteSubmit.py", line 425, in create_misp_event
    event = misp_create_event(distribution, threat_level_id, analysis, info, l_tags, publish, path)
  File "/opt/ail-framework//var/www/modules/PasteSubmit/Flask_PasteSubmit.py", line 134, in misp_create_event
    event = pymisp.new_event(distribution, threat_level_id,
AttributeError: 'PyMISP' object has no attribute 'new_event'
```

Could you please look in to it,
Thank you very much

**Comment by Terrtia** [comment]
Hi @petmi627 !

PyMISP doesn't support python 3.5 anymore. We plan to drop AIL 3.5 support soon.
92b71e02c3c186ad7e187a875699cd497b964ea4 force PyMISP to v2.4.119.1

We should switch to the latest version in the coming weeks.

you can run ``./update_thirdparty.sh`` to solve this error. Let me know if this solve your issue.

**Comment by petmi627** [comment]
Hi @Terrtia ,

Thank you very much, I pulled the change and launched the script `./update_thirdparty.sh`, restarted Ail and the problem was solved.
