### ISSUE TITLE
global.py error

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [CIRCL/AIL-framework#464]
Recieved this
```
File already exist /home/ubuntu/Apps/AIL-framework/PASTES/archive/pastebin.com_pro/2020/02/07/FUMC4RPe
Traceback (most recent call last):
  File "./Global.py", line 119, in <module>
    curr_file_content = f.read()
  File "/usr/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'Na')
```

**Comment by Terrtia** [comment]
Hi @Phil-ThePower-Pearce !
Thank you for the report !
Fixed with d8fbd72
