### ISSUE TITLE
Indexer.py 

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [CIRCL/AIL-framework#468]
Hi,
Whilst running the scripts Ive noticed this in the indexer

Indexing - 1580809702 : archive/pastebin.com_pro/2020/02/11/FjQhcqFk.gz
Indexing - 1580809702 : archive/gist.github.com/2020/02/11/sylr_b065e1fbd3de0c2ff095d83b969e6db4.gz
Indexing - 1580809702 : archive/pastebin.com_pro/2020/02/11/UQcU4SKv.gz
Indexing - 1580809702 : archive/pastebin.com_pro/2020/02/11/PhHjsK9A.gz
Indexing - 1580809702 : archive/ideone.com/2020/02/11/qYcdfx.gz
**bash: line 1: 20994 Killed                  /home/ubuntu/Apps/AIL-framework//AILENV/bin/python ./Indexer.py**

The indexer queue obviously stopped, Is there a way to restart a single screen/service again and redo the queue? The moldule information script doesnt work as reported previously.

**Comment by Terrtia** [comment]
Hi @Phil-ThePower-Pearce !

It seem like something on your server kill this script.

You can manually relaunch it:
- ``Screen -r Script_AIL``
- ``Crtl+a c``
- `. ./AILENV/bin/activate``
- ``cd bin``
- ``./Indexer.py``

**Comment by Phil-ThePower-Pearce** [comment]
How can I tell what killed it? As far as Im concerned its an aws ec2 t2.medium ubuntu 18.04 instance, up-to-date and only running ail and pystemon.

**Comment by Phil-ThePower-Pearce** [comment]
A new one today 

`Traceback (most recent call last):
  File "./Indexer.py", line 134, in <module>
    content=paste)
  File "/home/ubuntu/Apps/AIL-framework/AILENV/lib/python3.6/site-packages/whoosh/writing.py", line 483, in update_document
    with self.searcher() as s:
  File "/home/ubuntu/Apps/AIL-framework/AILENV/lib/python3.6/site-packages/whoosh/writing.py", line 297, in searcher
    return Searcher(self.reader(), **kwargs)
  File "/home/ubuntu/Apps/AIL-framework/AILENV/lib/python3.6/site-packages/whoosh/writing.py", line 639, in reader
    self.generation, reuse=reuse)
  File "/home/ubuntu/Apps/AIL-framework/AILENV/lib/python3.6/site-packages/whoosh/index.py", line 535, in _reader
    readers = [segreader(segment) for segment in segments]
  File "/home/ubuntu/Apps/AIL-framework/AILENV/lib/python3.6/site-packages/whoosh/index.py", line 535, in <listcomp>
    readers = [segreader(segment) for segment in segments]
  File "/home/ubuntu/Apps/AIL-framework/AILENV/lib/python3.6/site-packages/whoosh/index.py", line 524, in segreader
    generation=generation)
  File "/home/ubuntu/Apps/AIL-framework/AILENV/lib/python3.6/site-packages/whoosh/reading.py", line 620, in __init__
    self._terms = self._codec.terms_reader(self._storage, segment)
  File "/home/ubuntu/Apps/AIL-framework/AILENV/lib/python3.6/site-packages/whoosh/codec/whoosh3.py", line 122, in terms_reader
    postfile = segment.open_file(storage, self.POSTS_EXT)
  File "/home/ubuntu/Apps/AIL-framework/AILENV/lib/python3.6/site-packages/whoosh/codec/base.py", line 556, in open_file
    return storage.open_file(fname, **kwargs)
  File "/home/ubuntu/Apps/AIL-framework/AILENV/lib/python3.6/site-packages/whoosh/filedb/filestore.py", line 333, in open_file
    return self.a.open_file(name, *args, **kwargs)
  File "/home/ubuntu/Apps/AIL-framework/AILENV/lib/python3.6/site-packages/whoosh/filedb/compound.py", line 121, in open_file
    f = BufferFile(buf, name=name)
  File "/home/ubuntu/Apps/AIL-framework/AILENV/lib/python3.6/site-packages/whoosh/filedb/structfile.py", line 357, in __init__
    self.file = BytesIO(buf)
MemoryError
`

**Comment by Terrtia** [comment]
This seem to be a memory issue.
Are you processing large files ?

**Comment by Phil-ThePower-Pearce** [comment]
Im litteraly pulling the data from CIRCL feed

**Comment by mokaddem** [comment]
Hey, what are the specs of your system? How much memory is available?

**Comment by Phil-ThePower-Pearce** [comment]
aws ec2 t2.medium ubuntu 18.04 instance
2 vCPUs, 4Gb Memory

**Comment by Terrtia** [comment]
It seem like the Indexer run out of memory.
The minimum configuration is at least 2 CPUs and 8GB of memory.

**Comment by Phil-ThePower-Pearce** [comment]
Im rebuilding the ec2 instance with the above settings. Will retry

**Comment by Phil-ThePower-Pearce** [comment]
"
