### ISSUE TITLE
Error while updating 

### ISSUE THREAD

**Issue by Zakaren** [CIRCL/AIL-framework#472]
Hi there, 

I'm getting the below error while updating AIL. Could you have a look please ? 

```
Traceback (most recent call last):
  File "/home/debian/AIL-framework//bin/Update.py", line 362, in <module>
    list_upper_tags_remote = get_git_upper_tags_remote(current_tag[1:], is_fork)
  File "/home/debian/AIL-framework//bin/Update.py", line 191, in get_git_upper_tags_remote
    if last_tag not in list_upper_tags[-1][0]:
IndexError: list index out of range
        * Update Error
```

**Comment by Phil-ThePower-Pearce** [comment]
I also have this

**Comment by Terrtia** [comment]
Hi !
Thanks for the report !
ficed with  fd4b3e0
