### ISSUE TITLE
pystemon trouble: AttributeError: 'tuple' object has no attribute 'text'

### ISSUE THREAD

**Issue by vascospooren** [CIRCL/AIL-framework#483]
Hi all,

I set up AIL today and my next step is to collect data.
I'm following the steps as described in HOWTO.md

When I do step 3: Launch pystemon ``` ./pystemon ```
This is the output I get:
```bash
Site: safebin.net is disabled.
Site: slexy.org is enabled, adding to pool...
Site: pastebin.com is enabled, adding to pool...
Site: gist.github.com is disabled.
Site: pastebin.com_pro is disabled.
Site: codepad.org is disabled.
[2020-03-24 18:54:02,119] Using default IP address
[2020-03-24 18:54:02,120] Downloading list of new pastes from slexy.org. Will check again in 16 seconds
[2020-03-24 18:54:02,120] Using default IP address
[2020-03-24 18:54:02,120] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2020-03-24 18:54:02,121] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2020-03-24 18:54:02,122] Downloading list of new pastes from pastebin.com. Will check again in 49 seconds
[2020-03-24 18:54:02,122] Downloading url: http://pastebin.com/archive with proxy: None and user-agent: None
[2020-03-24 18:54:02,123] Downloading url: http://pastebin.com/archive with proxy: None and user-agent: None
[2020-03-24 18:54:02,267] Thread for pastebin.com crashed unexpectectly, recovering...: 'tuple' object has no attribute 'text'
[2020-03-24 18:54:02,267] Traceback (most recent call last):
  File "./pystemon.py", line 131, in run
    last_pasties = self.get_last_pasties()
  File "./pystemon.py", line 151, in get_last_pasties
    htmlPage = response.text
AttributeError: 'tuple' object has no attribute 'text'

[2020-03-24 18:54:02,604] Thread for slexy.org crashed unexpectectly, recovering...: 'tuple' object has no attribute 'text'
[2020-03-24 18:54:02,605] Traceback (most recent call last):
  File "./pystemon.py", line 131, in run
    last_pasties = self.get_last_pasties()
  File "./pystemon.py", line 151, in get_last_pasties
    htmlPage = response.text
AttributeError: 'tuple' object has no attribute 'text'

[2020-03-24 18:54:18,609] Downloading list of new pastes from slexy.org. Will check again in 23 seconds
[2020-03-24 18:54:18,609] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2020-03-24 18:54:18,610] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2020-03-24 18:54:18,798] Thread for slexy.org crashed unexpectectly, recovering...: 'tuple' object has no attribute 'text'
[2020-03-24 18:54:18,798] Traceback (most recent call last):
  File "./pystemon.py", line 131, in run
    last_pasties = self.get_last_pasties()
  File "./pystemon.py", line 151, in get_last_pasties
    htmlPage = response.text
AttributeError: 'tuple' object has no attribute 'text'

[2020-03-24 18:54:41,807] Downloading list of new pastes from slexy.org. Will check again in 19 seconds
[2020-03-24 18:54:41,808] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2020-03-24 18:54:41,808] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2020-03-24 18:54:42,002] Thread for slexy.org crashed unexpectectly, recovering...: 'tuple' object has no attribute 'text'
[2020-03-24 18:54:42,002] Traceback (most recent call last):
  File "./pystemon.py", line 131, in run
    last_pasties = self.get_last_pasties()
  File "./pystemon.py", line 151, in get_last_pasties
    htmlPage = response.text
AttributeError: 'tuple' object has no attribute 'text'
```

Does anyone know how I can fix this?
I just cloned the repo as told in the steps. I didn't change anything else.

Thanks in advance!

**Comment by vascospooren** [comment]
EDIT:

I'm using https://github.com/cvandeplas/pystemon.git for now instead of the one from CIRCL and this one is working.
