### ISSUE TITLE
Update third-party failed

### ISSUE THREAD

**Issue by xme** [CIRCL/AIL-framework#485]
It seems to be related to PyMISP but... 
Any idea?
```
Collecting git+https://github.com/MISP/PyMISP
  Cloning https://github.com/MISP/PyMISP to /tmp/pip-req-build-e074zxit
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-e074zxit/setup.py", line 7, in <module>
        import pymisp
      File "/tmp/pip-req-build-e074zxit/pymisp/__init__.py", line 26, in <module>
        from .abstract import AbstractMISP, MISPEncode, pymisp_json_default, MISPTag, Distribution, ThreatLevel, Analysis  # noqa
      File "/tmp/pip-req-build-e074zxit/pymisp/abstract.py", line 116
        self.__edited: bool = True  # As we create a new object, we assume it is edited
                     ^
    SyntaxError: invalid syntax

```

**Comment by xme** [comment]
Despites the fact that the web interface is not available, I see also a lot of error with other modules. Ex:

```
    self.entries: Dict[str, Entry] = {}
                ^
SyntaxError: invalid syntax
```

**Comment by xme** [comment]
Ok, RTFM... I upgraded to Python 3.7...
