### ISSUE TITLE
AIL framework not opening

### ISSUE THREAD

**Issue by annetteshajan** [CIRCL/AIL-framework#505]
I'm trying to just run the flask server and I get this error
Misp not connected
The HIVE not connected
VT submission is disabled
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'Splash_Manager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shajan/AIL-framework/var/www/Flask_server.py", line 41, in <module>
    from blueprints.crawler_splash import crawler_splash
  File "/home/shajan/AIL-framework/var/www/blueprints/crawler_splash.py", line 28, in <module>
    import crawlers
  File "/home/shajan/AIL-framework/bin/lib/crawlers.py", line 41, in <module>
    splash_manager_url = config_loader.get_config_str('Splash_Manager', 'splash_url')
  File "/home/shajan/AIL-framework/bin/lib/ConfigLoader.py", line 45, in get_config_str
    return self.cfg.get(section, key_name)
  File "/usr/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'Splash_Manager'

**Comment by xme** [comment]
+1

**Comment by Terrtia** [comment]
Hi @annetteshajan , @xme !
Thanks for the report !

Fixed with eec579c5d45bdf7abbf1359ad514d59340933f32

**Comment by xme** [comment]
Confirmed working, tx!

**Comment by Terrtia** [comment]
Thanks for the feedback !
