### ISSUE TITLE
Issue with pystemon -- How to fix ?

### ISSUE THREAD

**Issue by Skullack** [CIRCL/AIL-framework#553]
[2021-04-01 21:33:33,759] Downloading list of new pastes from pastebin.com_pro. Will check again in 50 seconds
[2021-04-01 21:33:33,759] Downloading url: https://scrape.pastebin.com/api_scraping.php?limit=500 with proxy: None and user-agent: None
[2021-04-01 21:33:33,759] Downloading url: https://scrape.pastebin.com/api_scraping.php?limit=500 with proxy: None and user-agent: None
[2021-04-01 21:33:34,470] Thread for pastebin.com_pro crashed unexpectectly, recovering...: 'tuple' object has no attribute 'text'
[2021-04-01 21:33:34,470] Traceback (most recent call last):
  File "pystemon.py", line 131, in run
    last_pasties = self.get_last_pasties()
  File "pystemon.py", line 151, in get_last_pasties
    htmlPage = response.text
AttributeError: 'tuple' object has no attribute 'text'

**Comment by lesleyxyz** [comment]
Please see https://github.com/CIRCL/pystemon/issues/4
Use https://github.com/cvandeplas/pystemon instead
