### ISSUE TITLE
Install failing Ubuntu 20.04 - Believe due to PyMISPGalaxies update

### ISSUE THREAD

**Issue by cybgit** [CIRCL/AIL-framework#591]
AIL fails to install on Unbuntu 20.04. 

This installed fine just last week on the same distro. 

I have raised an issue [here](https://github.com/MISP/PyMISPGalaxies/issues/8) as believe this relates to a recent update in PyMISPGalaxies

For completeness, here is the traceback with the errors

```
Installing collected packages: pytaxonomies
Successfully installed pytaxonomies-1.5.0
Collecting git+https://github.com/MISP/PyMISPGalaxies
  Cloning https://github.com/MISP/PyMISPGalaxies to /tmp/pip-req-build-h7spqapm
  Running command git clone --filter=blob:none --quiet https://github.com/MISP/PyMISPGalaxies /tmp/pip-req-build-h7spqapm
  Resolved https://github.com/MISP/PyMISPGalaxies to commit 14859ae37572c9d6278cbd56036dc0d0f0ad942f
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... - \ | done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 631, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 692, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/home/azureuser/ail-framework/AILENV/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'poetry.masonry'

user@hostxxxx:~/ail-framework$ ^C
```

**Comment by cybgit** [comment]
I've closed down the issue i raised in PyMISPGalaxies as believe this is the right place for this to be fixed

**Comment by cybgit** [comment]
Added as an issue on [this project](https://github.com/ail-project/ail-framework/issues/162) as i have noticed this repo is no longer maintained.
