### ISSUE TITLE
PystemonImporter .py error

### ISSUE THREAD

**Issue by pablogomezcalvo1996** [CIRCL/AIL-framework#597]
Hi,

Running the script with pystemon running correctly, it shows the next error:

Traceback (most recent call last):
  File "/root/ail-framework/bin/importer/./PystemonImporter.py", line 87, in <module>
    module.run()
  File "/root/ail-framework/bin/modules/abstract_module.py", line 131, in run
    message = self.get_message()
  File "/root/ail-framework/bin/importer/./PystemonImporter.py", line 79, in get_message
    return self.importer.importer()
  File "/root/ail-framework/bin/importer/./PystemonImporter.py", line 55, in importer
    return self.create_message(item_id, content, gzipped=gzipped, source='pystemon')
  File "/root/ail-framework/bin/importer/abstract_importer.py", line 92, in create_message
    content = self.b64(gzipped)
  File "/root/ail-framework/bin/importer/abstract_importer.py", line 72, in b64
    return base64.b64encode(content).decode()
  File "/usr/lib/python3.10/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'bool'

**Comment by Terrtia** [comment]
Hi @pablogomezcalvo1996 !
Thanks for the report !
Fixed with a0686eefcf005a4db17b19f498d0cfa9bcdbc18d
