### ISSUE TITLE
Issues with starting AIL Framework

### ISSUE THREAD

**Issue by vickywijek** [CIRCL/AIL-framework#608]
Hi, 

I have  installed AIL in my Ubuntu VM, but when I launch it with ./LAUNCH.sh -l  it gives me the following error. Can someone please help me fix the issue.

****************  AIL Successfully Updated  *****************

	* A screen is already launched
	* Launching KVROCKS servers
	* Launching logging process
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
	* Checking configuration
Config File: Nothing to update
Config File: Nothing to update
	* Configuration up-to-date
	* Launching core scripts ...
~/AIL-framework/bin ~/AIL-framework
Traceback (most recent call last):
  File "/home/user1/AIL-framework/bin/./AIL_Init.py", line 19, in <module>
    from lib import ail_core
  File "/home/user1/AIL-framework/bin/lib/ail_core.py", line 12, in <module>
    from lib.ConfigLoader import ConfigLoader
  File "/home/user1/AIL-framework/bin/lib/ConfigLoader.py", line 12, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
~/AIL-framework
	* Launching scripts
	* Launching Flask server
user1@user1-VMware-Virtual-Platform:~/AIL-framework/bin$

**Comment by vickywijek** [comment]
Hi 
Ubuntu 24.04 LTS   .

No I did not have any issue.

Can you please tell me how to check of AILENV is correctly installed?

**Comment by vickywijek** [comment]
Hi @Terrtia 

Thanks

OS -> Ubuntu 24.04 LTS   .

No I did not have any issue during the installation. I simply did an automated installation following the instructions listed at -> https://helga.circl.lu/AIL/ail-framework/src/commit/246621f6638f88b73d61e8a803e649d88a315a2f

How can I check if AILENV is set up correctly?

**Comment by Terrtia** [comment]
You can Launch the module and API tests:

1) Launch AIL:
```bash
LAUNCH.sh -l
```

2) Run the tests:
```bash
LAUNCH.sh -t
```
